#!/usr/bin/env sage -python
"""
Generate SagemathBuiltins.kt and SagemathTypes.kt from a running SageMath
installation.

Run from a shell where `sage` is on PATH:

    sage -python scripts/generate_builtins.py

This walks ``sage.all`` (which is what ``.sage`` files implicitly do via
``from sage.all import *``), classifies every public name into either a
type/class or a callable/value, and rewrites the two Kotlin source files
under ``src/main/kotlin/com/renpe/intellij/sagemath/lang/``.

The two Kotlin files are intentionally large but flat: each is a single
``object`` with one frozen ``Set<String>`` so lookup at lex time is O(1).
"""

from __future__ import annotations

import inspect
import pathlib
import re
import sys

KOTLIN_PACKAGE = "com.renpe.intellij.sagemath.lang"
TARGET_DIR = pathlib.Path(__file__).resolve().parent.parent / "src" / "main" / "kotlin" / "com" / "renpe" / "intellij" / "sagemath" / "lang"

IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Names that we deliberately keep out of either list because they are
# already in [SagemathKeywords] (the lexer matches keywords first, but it
# is cleaner to also strip them here so the generated file does not list
# them).
SKIP = {
    "True", "False", "None", "Ellipsis", "NotImplemented",
    "and", "or", "not", "in", "is",
    "if", "elif", "else", "for", "while", "break", "continue",
    "return", "yield", "try", "except", "finally", "raise",
    "with", "as", "pass", "match", "case", "assert",
    "def", "class", "lambda", "async", "await", "global", "nonlocal",
    "import", "from", "del", "print", "exec",
    "self", "cls",
    "pi", "e", "I", "oo", "infinity", "Infinity", "NaN",
    "golden_ratio", "euler_gamma", "catalan", "khinchin",
    "twinprime", "mertens", "glaisher",
}


def classify() -> tuple[list[str], list[str]]:
    try:
        import sage.all as sage_all  # type: ignore[import-not-found]
    except ImportError as e:
        sys.exit(f"sage.all could not be imported. Run via `sage -python`. ({e})")

    types: set[str] = set()
    builtins: set[str] = set()

    for name in dir(sage_all):
        if not IDENT_RE.match(name):
            continue
        if name.startswith("_"):
            continue
        if name in SKIP:
            continue
        try:
            value = getattr(sage_all, name)
        except Exception:
            continue
        if inspect.isclass(value):
            types.add(name)
        else:
            # Callables, constants, modules, instances — everything else.
            builtins.add(name)

    return sorted(types), sorted(builtins)


def render(name: str, kind: str, names: list[str]) -> str:
    """Render a Kotlin object with a single Set<String> NAMES."""
    lines = [
        f"package {KOTLIN_PACKAGE}",
        "",
        "/**",
        f" * Sage {kind} names exposed at the top level of `sage.all`.",
        " *",
        " * Auto-generated by `scripts/generate_builtins.py`. Do not edit by hand —",
        f" * regenerate against the target Sage version with `sage -python scripts/generate_builtins.py`.",
        " */",
        f"internal object {name} {{",
        "",
        "    val NAMES: Set<String> = setOf(",
    ]
    # Six names per line keeps the file roughly square.
    chunk = 6
    for i in range(0, len(names), chunk):
        row = ", ".join(f"\"{n}\"" for n in names[i : i + chunk])
        lines.append(f"        {row},")
    lines += [
        "    )",
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    types, builtins = classify()
    print(f"Found {len(types)} types and {len(builtins)} builtins in sage.all")
    TARGET_DIR.mkdir(parents=True, exist_ok=True)
    (TARGET_DIR / "SagemathTypes.kt").write_text(render("SagemathTypes", "category/type", types))
    (TARGET_DIR / "SagemathBuiltins.kt").write_text(render("SagemathBuiltins", "built-in function/value", builtins))
    print("Wrote SagemathTypes.kt and SagemathBuiltins.kt")


if __name__ == "__main__":
    main()
