package com.renpe.intellij.sagemath.lang

/**
 * Keyword sets for SageMath. Sage is a Python superset, so the keyword
 * set is Python's plus a handful of Sage-specific identifiers that the
 * preparser treats specially (e.g. `var`, generator-arrow notation).
 *
 * The very large name sets — type categories and built-in functions —
 * live in [SagemathTypes] and [SagemathBuiltins] respectively, both of
 * which are autogenerated from a running Sage install via
 * `scripts/generate_builtins.py`.
 */
internal object SagemathKeywords {

    val CONTROL: Set<String> = setOf(
        "if", "elif", "else", "for", "while", "break", "continue",
        "return", "yield", "try", "except", "finally", "raise",
        "with", "as", "pass", "match", "case", "assert",
    )

    val DECL: Set<String> = setOf(
        "def", "class", "lambda", "async", "await",
        "global", "nonlocal",
    )

    val STATEMENT: Set<String> = setOf(
        "import", "from", "del", "print", "exec",
    )

    val OPERATOR_WORD: Set<String> = setOf(
        "and", "or", "not", "in", "is",
    )

    val CONSTANT: Set<String> = setOf(
        // Python literals
        "True", "False", "None", "Ellipsis", "NotImplemented",
        // Sage mathematical constants exposed at top level. Many of these
        // are *also* names in [SagemathBuiltins], but we want them coloured
        // as constants, so they take precedence in the lexer.
        "pi", "e", "I", "oo", "infinity", "Infinity", "NaN",
        "golden_ratio", "euler_gamma", "catalan", "khinchin",
        "twinprime", "mertens", "glaisher",
    )

    val SELF: Set<String> = setOf("self", "cls")

    /** ~hundreds of Sage category/type identifiers — see [SagemathTypes]. */
    val TYPE_CATEGORY: Set<String> get() = SagemathTypes.NAMES

    /** Thousands of Sage built-in function names — see [SagemathBuiltins]. */
    val BUILTIN_FUNCTION: Set<String> get() = SagemathBuiltins.NAMES
}
